version: "3.9"

services:
  backend:
    build: .
    container_name: grolf-backend
    ports:
      - "3001:3001"
    environment:
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: grolf
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: grolf-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: grolf
    volumes:
      - grolf-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

volumes:
  grolf-data:
